;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Game.Event.Chest.Damage",DevComment="")
+GameplayTagList=(Tag="Game.Event.Chest.FireRate",DevComment="")
+GameplayTagList=(Tag="Game.Event.Chest.Health",DevComment="")
+GameplayTagList=(Tag="Game.Event.Chest.MoveSpeed",DevComment="")
+GameplayTagList=(Tag="Game.Event.Chest.ProjectileCount",DevComment="")
+GameplayTagList=(Tag="Game.Event.Combat.Fire",DevComment="")
+GameplayTagList=(Tag="Game.Event.Gate.Add",DevComment="")
+GameplayTagList=(Tag="Game.Event.Gate.Damage",DevComment="")
+GameplayTagList=(Tag="Game.Event.Gate.FireRate",DevComment="")
+GameplayTagList=(Tag="Game.Event.Gate.MoveSpeed",DevComment="")
+GameplayTagList=(Tag="Game.Event.Gate.Multiply",DevComment="")
+GameplayTagList=(Tag="Game.Event.Gate.ProjectileCount",DevComment="")
+GameplayTagList=(Tag="Game.Event.Map.GenerateNext",DevComment="")
+GameplayTagList=(Tag="Game.Event.Monster.Death",DevComment="")
+GameplayTagList=(Tag="Game.Event.Monster.Generate",DevComment="")
+GameplayTagList=(Tag="Game.Event.Monster.Overlap",DevComment="")
+GameplayTagList=(Tag="Game.Event.Montage.Shoot",DevComment="")
+GameplayTagList=(Tag="Multiply",DevComment="")

